const POST_ACTIONS = {
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_ERRORS: "SET_ERRORS",
  FETCH_POSTS: "FETCH_POSTS",
  SET_POSTS: "SET_POSTS",
  SEARCH_POST: "SEARCH_POST"
};

export default POST_ACTIONS;
